{% set version = "8.7.0" %}

package:
  name: dtrx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dtrx/dtrx-{{ version }}.tar.gz
  sha256: d7c58048cd4a0e05337f0e0e01b05ad9ebc2b450a0f6706afc4b69abea81096f

build:
  entry_points:
    - dtrx = dtrx.dtrx:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - bzip2
    - p7zip
    - python >={{ python_min }}
    - unzip
    - xz-tools

test:
  imports:
    - dtrx
  commands:
    - pip check
    - dtrx --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dtrx-py/dtrx
  summary: Script to intelligently extract multiple archive types
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - danielnachun
